# Generated by Django 4.0.4 on 2023-03-26 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('audio1', models.FileField(upload_to='')),
                ('audio2', models.FileField(upload_to='')),
                ('audio3', models.FileField(upload_to='')),
                ('audio4', models.FileField(upload_to='')),
                ('audio5', models.FileField(upload_to='')),
                ('embeddings1', models.TextField()),
                ('embeddings2', models.TextField()),
                ('embeddings3', models.TextField()),
                ('embeddings4', models.TextField()),
                ('embeddings5', models.TextField()),
            ],
        ),
    ]
