# Generated by Django 4.0.4 on 2023-04-05 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio1', models.FileField(upload_to='')),
                ('audio2', models.FileField(upload_to='')),
                ('audio3', models.FileField(upload_to='')),
                ('audio4', models.FileField(upload_to='')),
                ('audio5', models.FileField(upload_to='')),
                ('audio6', models.FileField(upload_to='')),
                ('audio7', models.FileField(upload_to='')),
                ('audio8', models.FileField(upload_to='')),
                ('audio9', models.FileField(upload_to='')),
                ('audio10', models.FileField(upload_to='')),
            ],
        ),
    ]
