# Generated by Django 4.1.7 on 2023-04-03 11:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('audio0', models.FileField(upload_to='')),
                ('audio1', models.FileField(upload_to='')),
                ('audio2', models.FileField(upload_to='')),
                ('audio3', models.FileField(upload_to='')),
                ('audio4', models.FileField(upload_to='')),
                ('audio5', models.FileField(upload_to='')),
                ('audio6', models.FileField(upload_to='')),
                ('audio7', models.FileField(upload_to='')),
                ('audio8', models.FileField(upload_to='')),
                ('audio9', models.FileField(upload_to='')),
                ('embeddings0', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('embeddings1', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('embeddings2', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('embeddings3', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('embeddings4', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('embeddings5', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('embeddings6', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('embeddings7', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('embeddings8', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('embeddings9', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
            ],
        ),
    ]
