# Generated by Django 4.1.7 on 2023-04-03 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='audio0',
        ),
        migrations.RemoveField(
            model_name='files',
            name='audio1',
        ),
        migrations.RemoveField(
            model_name='files',
            name='audio2',
        ),
        migrations.RemoveField(
            model_name='files',
            name='audio3',
        ),
        migrations.RemoveField(
            model_name='files',
            name='audio4',
        ),
        migrations.RemoveField(
            model_name='files',
            name='audio5',
        ),
        migrations.RemoveField(
            model_name='files',
            name='audio6',
        ),
        migrations.RemoveField(
            model_name='files',
            name='audio7',
        ),
        migrations.RemoveField(
            model_name='files',
            name='audio8',
        ),
        migrations.RemoveField(
            model_name='files',
            name='audio9',
        ),
    ]
