# Generated by Django 4.1.7 on 2023-04-03 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2', '0002_remove_files_audio0_remove_files_audio1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='id',
        ),
        migrations.AddField(
            model_name='files',
            name='phone_no',
            field=models.BigIntegerField(default=1547896547, max_length=10, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
