# Generated by Django 4.1.7 on 2023-04-03 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2', '0003_remove_files_id_files_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='audio0',
            field=models.FileField(default=[2.2], upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='files',
            name='audio1',
            field=models.FileField(default=[2.2], upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='files',
            name='audio2',
            field=models.FileField(default=[2.2], upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='files',
            name='audio3',
            field=models.FileField(default=[2.2], upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='files',
            name='audio4',
            field=models.FileField(default=[2.2], upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='files',
            name='audio5',
            field=models.FileField(default=[2.2], upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='files',
            name='audio6',
            field=models.FileField(default=[2.2], upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='files',
            name='audio7',
            field=models.FileField(default=[2.2], upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='files',
            name='audio8',
            field=models.FileField(default=[2.2], upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='files',
            name='audio9',
            field=models.FileField(default=[2.2], upload_to=''),
            preserve_default=False,
        ),
    ]
