# Generated by Django 4.1.7 on 2023-04-04 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2', '0005_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='audio0',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='files',
            name='audio1',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='files',
            name='audio2',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='files',
            name='audio3',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='files',
            name='audio4',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='files',
            name='audio5',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='files',
            name='audio6',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='files',
            name='audio7',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='files',
            name='audio8',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='files',
            name='audio9',
            field=models.BinaryField(),
        ),
    ]
