# Generated by Django 4.1.7 on 2023-04-04 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2', '0008_files_embeddings0_files_embeddings1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='audio0',
            field=models.FileField(upload_to='C:\\Users\\Sarvesh\\Desktop\\p2\\p2/media'),
        ),
        migrations.AlterField(
            model_name='files',
            name='audio1',
            field=models.FileField(upload_to='C:\\Users\\Sarvesh\\Desktop\\p2\\p2/media'),
        ),
        migrations.AlterField(
            model_name='files',
            name='audio2',
            field=models.FileField(upload_to='C:\\Users\\Sarvesh\\Desktop\\p2\\p2/media'),
        ),
        migrations.AlterField(
            model_name='files',
            name='audio3',
            field=models.FileField(upload_to='C:\\Users\\Sarvesh\\Desktop\\p2\\p2/media'),
        ),
        migrations.AlterField(
            model_name='files',
            name='audio4',
            field=models.FileField(upload_to='C:\\Users\\Sarvesh\\Desktop\\p2\\p2/media'),
        ),
        migrations.AlterField(
            model_name='files',
            name='audio5',
            field=models.FileField(upload_to='C:\\Users\\Sarvesh\\Desktop\\p2\\p2/media'),
        ),
        migrations.AlterField(
            model_name='files',
            name='audio6',
            field=models.FileField(upload_to='C:\\Users\\Sarvesh\\Desktop\\p2\\p2/media'),
        ),
        migrations.AlterField(
            model_name='files',
            name='audio7',
            field=models.FileField(upload_to='C:\\Users\\Sarvesh\\Desktop\\p2\\p2/media'),
        ),
        migrations.AlterField(
            model_name='files',
            name='audio8',
            field=models.FileField(upload_to='C:\\Users\\Sarvesh\\Desktop\\p2\\p2/media'),
        ),
        migrations.AlterField(
            model_name='files',
            name='audio9',
            field=models.FileField(upload_to='C:\\Users\\Sarvesh\\Desktop\\p2\\p2/media'),
        ),
    ]
