# Generated by Django 4.1.7 on 2023-04-04 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p2', '0009_alter_files_audio0_alter_files_audio1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='embeddings0',
        ),
        migrations.RemoveField(
            model_name='files',
            name='embeddings1',
        ),
        migrations.RemoveField(
            model_name='files',
            name='embeddings2',
        ),
        migrations.RemoveField(
            model_name='files',
            name='embeddings3',
        ),
        migrations.RemoveField(
            model_name='files',
            name='embeddings4',
        ),
        migrations.RemoveField(
            model_name='files',
            name='embeddings5',
        ),
        migrations.RemoveField(
            model_name='files',
            name='embeddings6',
        ),
        migrations.RemoveField(
            model_name='files',
            name='embeddings7',
        ),
        migrations.RemoveField(
            model_name='files',
            name='embeddings8',
        ),
        migrations.RemoveField(
            model_name='files',
            name='embeddings9',
        ),
    ]
