# Generated by Django 4.1.7 on 2023-04-05 11:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2', '0011_alter_files_audio0_alter_files_audio1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='embeddings0',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=[2.2]), default=[2.2], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='files',
            name='embeddings1',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=[2.2]), default=[2.2], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='files',
            name='embeddings2',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=[2.2]), default=[2.2], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='files',
            name='embeddings3',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=[2.2]), default=[2.2], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='files',
            name='embeddings4',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=[2.2]), default=[2.2], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='files',
            name='embeddings5',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=[2.2]), default=[2.2], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='files',
            name='embeddings6',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=[2.2]), default=[2.2], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='files',
            name='embeddings7',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=[2.2]), default=[2.2], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='files',
            name='embeddings8',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=[2.2]), default=[2.2], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='files',
            name='embeddings9',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=[2.2]), default=[2.2], size=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='files',
            name='audio0',
            field=models.FileField(default=None, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='files',
            name='audio1',
            field=models.FileField(default=None, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='files',
            name='audio2',
            field=models.FileField(default=None, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='files',
            name='audio3',
            field=models.FileField(default=None, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='files',
            name='audio4',
            field=models.FileField(default=None, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='files',
            name='audio5',
            field=models.FileField(default=None, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='files',
            name='audio6',
            field=models.FileField(default=None, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='files',
            name='audio7',
            field=models.FileField(default=None, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='files',
            name='audio8',
            field=models.FileField(default=None, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='files',
            name='audio9',
            field=models.FileField(default=None, upload_to='media/'),
        ),
    ]
