# Generated by Django 4.1.7 on 2023-04-05 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2', '0012_files_embeddings0_files_embeddings1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='embeddings0',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='files',
            name='embeddings1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='files',
            name='embeddings2',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='files',
            name='embeddings3',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='files',
            name='embeddings4',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='files',
            name='embeddings5',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='files',
            name='embeddings6',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='files',
            name='embeddings7',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='files',
            name='embeddings8',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='files',
            name='embeddings9',
            field=models.TextField(),
        ),
    ]
