# Generated by Django 4.1.7 on 2023-04-06 14:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2', '0014_name_audio_name_emb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='name',
            name='emb',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None), size=None),
        ),
    ]
