# Generated by Django 4.1.7 on 2023-04-06 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2', '0015_alter_name_emb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='phone_no',
        ),
        migrations.RemoveField(
            model_name='name',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='name',
            name='emb',
        ),
        migrations.RemoveField(
            model_name='name',
            name='phone',
        ),
        migrations.AddField(
            model_name='name',
            name='audio0',
            field=models.FilePathField(default=None, path='media/'),
        ),
        migrations.AddField(
            model_name='name',
            name='audio1',
            field=models.FilePathField(default=None, path='media/'),
        ),
        migrations.AddField(
            model_name='name',
            name='audio2',
            field=models.FilePathField(default=None, path='media/'),
        ),
        migrations.AddField(
            model_name='name',
            name='audio3',
            field=models.FilePathField(default=None, path='media/'),
        ),
        migrations.AddField(
            model_name='name',
            name='audio4',
            field=models.FilePathField(default=None, path='media/'),
        ),
        migrations.AddField(
            model_name='name',
            name='audio5',
            field=models.FilePathField(default=None, path='media/'),
        ),
        migrations.AddField(
            model_name='name',
            name='audio6',
            field=models.FilePathField(default=None, path='media/'),
        ),
        migrations.AddField(
            model_name='name',
            name='audio7',
            field=models.FilePathField(default=None, path='media/'),
        ),
        migrations.AddField(
            model_name='name',
            name='audio8',
            field=models.FilePathField(default=None, path='media/'),
        ),
        migrations.AddField(
            model_name='name',
            name='audio9',
            field=models.FilePathField(default=None, path='media/'),
        ),
        migrations.AddField(
            model_name='name',
            name='email',
            field=models.EmailField(default=1, max_length=255, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='files',
            name='email',
            field=models.EmailField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
