# Generated by Django 4.1.7 on 2023-04-06 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2', '0017_alter_name_audio0_alter_name_audio1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='name',
            name='audio0',
            field=models.FilePathField(default=None, path='tp/<django.db.models.fields.EmailField>/'),
        ),
        migrations.AlterField(
            model_name='name',
            name='audio1',
            field=models.FilePathField(default=None, path='tp/<django.db.models.fields.EmailField>/'),
        ),
        migrations.AlterField(
            model_name='name',
            name='audio2',
            field=models.FilePathField(default=None, path='tp/<django.db.models.fields.EmailField>/'),
        ),
        migrations.AlterField(
            model_name='name',
            name='audio3',
            field=models.FilePathField(default=None, path='tp/<django.db.models.fields.EmailField>/'),
        ),
        migrations.AlterField(
            model_name='name',
            name='audio4',
            field=models.FilePathField(default=None, path='tp/<django.db.models.fields.EmailField>/'),
        ),
        migrations.AlterField(
            model_name='name',
            name='audio5',
            field=models.FilePathField(default=None, path='tp/<django.db.models.fields.EmailField>/'),
        ),
        migrations.AlterField(
            model_name='name',
            name='audio6',
            field=models.FilePathField(default=None, path='tp/<django.db.models.fields.EmailField>/'),
        ),
        migrations.AlterField(
            model_name='name',
            name='audio7',
            field=models.FilePathField(default=None, path='tp/<django.db.models.fields.EmailField>/'),
        ),
        migrations.AlterField(
            model_name='name',
            name='audio8',
            field=models.FilePathField(default=None, path='tp/<django.db.models.fields.EmailField>/'),
        ),
        migrations.AlterField(
            model_name='name',
            name='audio9',
            field=models.FilePathField(default=None, path='tp/<django.db.models.fields.EmailField>/'),
        ),
    ]
