# Generated by Django 4.1.7 on 2023-04-06 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2', '0019_remove_name_audio1_alter_name_audio0_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='name',
            name='audio1',
            field=models.FilePathField(default=None, path='C:/<django.db.models.fields.EmailField>'),
        ),
    ]
