# Generated by Django 4.1.7 on 2023-04-06 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p2', '0020_name_audio1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='name',
            name='audio0',
        ),
        migrations.RemoveField(
            model_name='name',
            name='audio1',
        ),
        migrations.RemoveField(
            model_name='name',
            name='audio2',
        ),
        migrations.RemoveField(
            model_name='name',
            name='audio3',
        ),
        migrations.RemoveField(
            model_name='name',
            name='audio4',
        ),
        migrations.RemoveField(
            model_name='name',
            name='audio5',
        ),
        migrations.RemoveField(
            model_name='name',
            name='audio6',
        ),
        migrations.RemoveField(
            model_name='name',
            name='audio7',
        ),
        migrations.RemoveField(
            model_name='name',
            name='audio8',
        ),
        migrations.RemoveField(
            model_name='name',
            name='audio9',
        ),
    ]
