# Generated by Django 4.1.7 on 2023-04-06 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2', '0023_alter_files_audio0_alter_files_audio1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='audio0',
            field=models.FileField(default=None, upload_to='media/None'),
        ),
    ]
