# Generated by Django 4.1.7 on 2023-04-06 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2', '0027_alter_files_audio0_alter_files_audio1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='audio0',
            field=models.FileField(default=None, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='files',
            name='audio1',
            field=models.FileField(default=None, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='files',
            name='audio2',
            field=models.FileField(default=None, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='files',
            name='audio3',
            field=models.FileField(default=None, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='files',
            name='audio4',
            field=models.FileField(default=None, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='files',
            name='audio5',
            field=models.FileField(default=None, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='files',
            name='audio6',
            field=models.FileField(default=None, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='files',
            name='audio7',
            field=models.FileField(default=None, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='files',
            name='audio8',
            field=models.FileField(default=None, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='files',
            name='audio9',
            field=models.FileField(default=None, upload_to='media/'),
        ),
    ]
