# Generated by Django 4.1.7 on 2023-04-07 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2', '0028_alter_files_audio0_alter_files_audio1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='name',
            name='audio0',
        ),
        migrations.RemoveField(
            model_name='name',
            name='audio1',
        ),
        migrations.RemoveField(
            model_name='name',
            name='audio2',
        ),
        migrations.RemoveField(
            model_name='name',
            name='audio3',
        ),
        migrations.RemoveField(
            model_name='name',
            name='audio4',
        ),
        migrations.RemoveField(
            model_name='name',
            name='audio5',
        ),
        migrations.RemoveField(
            model_name='name',
            name='audio6',
        ),
        migrations.RemoveField(
            model_name='name',
            name='audio7',
        ),
        migrations.RemoveField(
            model_name='name',
            name='audio8',
        ),
        migrations.RemoveField(
            model_name='name',
            name='audio9',
        ),
        migrations.AddField(
            model_name='name',
            name='embeddings0',
            field=models.TextField(default='1'),
        ),
        migrations.AddField(
            model_name='name',
            name='embeddings1',
            field=models.TextField(default='1'),
        ),
        migrations.AddField(
            model_name='name',
            name='embeddings2',
            field=models.TextField(default='1'),
        ),
        migrations.AddField(
            model_name='name',
            name='embeddings3',
            field=models.TextField(default='1'),
        ),
        migrations.AddField(
            model_name='name',
            name='embeddings4',
            field=models.TextField(default='1'),
        ),
        migrations.AddField(
            model_name='name',
            name='embeddings5',
            field=models.TextField(default='1'),
        ),
        migrations.AddField(
            model_name='name',
            name='embeddings6',
            field=models.TextField(default='1'),
        ),
        migrations.AddField(
            model_name='name',
            name='embeddings7',
            field=models.TextField(default='1'),
        ),
        migrations.AddField(
            model_name='name',
            name='embeddings8',
            field=models.TextField(default='1'),
        ),
        migrations.AddField(
            model_name='name',
            name='embeddings9',
            field=models.TextField(default='1'),
        ),
    ]
